### ISSUE TITLE
Prepare for the public disclosure

### ISSUE THREAD

**Issue by hanjukim** [terra-project/terra-wallet-ios#1]
This repo will enable developers to add features that requires create, load and sign transactions to their apps.

@ouiliame and @path0509 will review and update this repo to be made public from next week.

**Comment by path0509** [comment]
Libraries were included terra-wallet-ios
- MIT License / https://github.com/goldennetwork/GoldenKeystore
- MIT License / https://github.com/trustwallet/trezor-crypto-ios

**Comment by ouiliame** [comment]
Are there any tests ?

**Comment by path0509** [comment]
## getNewWallet()
this method generate a wallet info(privateKey, publicKey, terraAddress, mnemonic).

in TerraStation, i tried recover using generated mnemonic.
And Compair Terra addresses(generated by me and TerraStation).

## getNewWalletFromSeed(mnemonic, bip)
this method generate a wallet info(privateKey, publicKey, terraAddress).

in TerraStation, i tried generate new wallet info.
And i call this method(getNewWalletFromSeed) using generated(by TerraStation) mnemonic.
And Compair Terra addresses(generated by me and TerraStation).

## sign(tx, sequence, account_number, chain_id, hexPrivateKey, hexPublicKey)
this method generate tx Message

- sequence: "15" // for Testnet, https://soju-lcd.terra.dev/auth/accounts/{YOUR ADDRESS}
- accountNumber: "406" // for Testnet, https://soju-lcd.terra.dev/auth/accounts/{YOUR ADDRESS}
- chainId: "soju-0013" // for Testnet, https://soju-lcd.terra.dev/blocks/latest
- hexPrivateKey: "99b555956f56a2889c78594cfac8d8aa6d0a6e75bd3ccfefb5248b6b83d8096c"
- hexPublicKey: "0352105a7248e226cbb913aad4d5997cf03db9e6caf03dd9a1d168442325d4ff1f"
- tx : 
~~~json
{"msg":[{"type":"bank/MsgSend","value":{"from_address":"terra14aqr0fwhsh334qpeu39wuzdt9hkw2pwvwnyvh6","to_address":"terra1y56xnxa2aaxtuc3rpntgxx0qchyzy2wp7dqgy3","amount":[{"denom":"uluna","amount":"50"}]}}],"fee":{"amount":[{"denom":"uluna","amount":"50"}],"gas":"200000"},"signatures":null,"memo":"memo"}
~~~

- result of this method. (it can be post)
~~~json
{"mode":"block","tx":{"msg":[{"type":"bank\/MsgSend","value":{"from_address":"terra14aqr0fwhsh334qpeu39wuzdt9hkw2pwvwnyvh6","amount":[{"denom":"uluna","amount":"50"}],"to_address":"terra1y56xnxa2aaxtuc3rpntgxx0qchyzy2wp7dqgy3"}}],"signatures":[{"account_number":"406","signature":"6ihKsc221nT8aAacaqaZ3J4kZgN5+w6PIrEZK8SU68Q48EA2yJ7m0SYgYvU0\/r3Af8aMi0eO2GH4DPziSBlxFA==","sequence":"15","pub_key":{"type":"tendermint\/PubKeySecp256k1","value":"A1IQWnJI4ibLuROq1NWZfPA9uebK8D3ZodFoRCMl1P8f"}}],"fee":{"amount":[{"denom":"uluna","amount":"50"}],"gas":"200000"},"memo":"memo"}}
~~~

i made a transaction(transfer, swap) and posted.
i got successful results. (https://finder.terra.money/soju-0013/account/terra14aqr0fwhsh334qpeu39wuzdt9hkw2pwvwnyvh6)


i did same test terra-wallet-java too.

**Comment by ouiliame** [comment]
Cool, good job! I think if you write these tests as XCTest and JUnit tests and include them with our framework, will give our end-users a lot more confidence. Can you add those?

**Comment by path0509** [comment]
I think so. i added ios testcase(https://github.com/terra-project/terra-wallet-ios/blob/master/Example/Tests/Tests.swift).

1. Test 100 times generate, recover.
2. Test transfer to another address realtime.
3. Test market swap realtime.
